# Generated by Django 5.1.3 on 2024-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_blog_tags_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
