# Generated by Django 5.1.3 on 2024-11-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='subject',
            field=models.TextField(max_length=100),
        ),
    ]
