# Generated by Django 5.1.3 on 2024-11-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_enquiry_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='deleted_at',
            new_name='hidden_at',
        ),
    ]
