# Generated by Django 5.1.3 on 2025-01-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
